### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by jm-riley** [jork41989/cumulusNote#1]
### `songs`
- [x] index on `user_id`
- [x]  `name` shouldn't have a unique constraint, unless you want to make it so that a given user can only have one song by a certain name ( [user_id, name] unique: true )
- [x] you still have 'index on url' even though there is no `url` column

### `comments`
- [x] add index on all foreign keys

Looks great!

**Comment by jork41989** [comment]
Adjustments made, thanks! Let me know if you see anything else.
