### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by jm-riley** [jork41989/cumulusNote#2]
### `songs`
- [x] needs a "song file" to be stored for each song in state
- [x] keep the `foreign_key` uniform for every song, either `user_id`, or `artist_id`
- [x] would be nice to have an array of `comment_ids` for a given song

### `comments`
- [x] `comments` should have a `body`
- [x] should have a key of `id` that matches the top level key in `comments` slice of state
- [x] needs a `user_id` or `author_id` of whoever created the `comment`

Sample state looks good!

**Comment by jork41989** [comment]
Made adjustments, take a look! Thanks again!
